// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbibeckqtywnlsquyywu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaWJlY2txdHl3bmxzcXV5eXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTA5MjcsImV4cCI6MjA1OTUyNjkyN30.9-R7MBSFZmCIJgKwPqUZ-seELPYpCLdxTwHmrtn7lXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);